"""add soft deletion and corroboration fields

Revision ID: 0dafecf04f65
Revises: fc324d2ad8ad
Create Date: 2026-10-05 00:28:27.415667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dafecf04f65"
down_revision: Union[str, Sequence[str], None] = "fc324d2ad8ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alert_logs", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "osint_sources",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "threat_events",
        sa.Column("corroborated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "threat_events",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threat_events", "deleted_at")
    op.drop_column("threat_events", "corroborated_at")
    op.drop_column("osint_sources", "deleted_at")
    op.drop_column("alert_logs", "deleted_at")
    # ### end Alembic commands ###
