"""add alert actions table

Revision ID: 226eb47c96bb
Revises: 1157e48637ae
Create Date: 2026-08-27 21:06:42.089317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '226eb47c96bb'
down_revision: Union[str, Sequence[str], None] = '1157e48637ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_event_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['threat_event_id'], ['threat_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_actions_status'), 'alert_actions', ['status'], unique=False)
    op.create_index(op.f('ix_alert_actions_threat_event_id'), 'alert_actions', ['threat_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_actions_threat_event_id'), table_name='alert_actions')
    op.drop_index(op.f('ix_alert_actions_status'), table_name='alert_actions')
    op.drop_table('alert_actions')
    # ### end Alembic commands ###
