"""connect five table relationships

Revision ID: c61901464e7c
Revises: 017083aec8b1
Create Date: 2026-09-20 04:21:44.973529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c61901464e7c"
down_revision: Union[str, Sequence[str], None] = "017083aec8b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_camera_states_camera_id", "camera_states", ["camera_id"]
    )
    op.add_column("threat_events", sa.Column("source_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_threat_events_source_id"), "threat_events", ["source_id"], unique=False
    )
    op.create_foreign_key(
        "fk_threat_events_source_id_osint_sources",
        "threat_events",
        "osint_sources",
        ["source_id"],
        ["source_id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_threat_events_camera_id_camera_states",
        "threat_events",
        "camera_states",
        ["camera_id"],
        ["camera_id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_threat_events_camera_id_camera_states", "threat_events", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_threat_events_source_id_osint_sources", "threat_events", type_="foreignkey"
    )
    op.drop_index(op.f("ix_threat_events_source_id"), table_name="threat_events")
    op.drop_column("threat_events", "source_id")
    op.drop_constraint("uq_camera_states_camera_id", "camera_states", type_="unique")
    # ### end Alembic commands ###
